import Link from "next/link";
import {
  ArrowRight,
  BarChart3,
  Bot,
  CheckCircle2,
  ChevronRight,
  Clock,
  DollarSign,
  Flame,
  Gauge,
  MessageSquare,
  RefreshCw,
  Reply,
  ShieldCheck,
  Sparkles,
  Timer,
  TrendingUp,
  Users2,
  Workflow,
  Zap,
} from "lucide-react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { FeaturesCta } from "./FeaturesCta";
import { FeaturesTestimonials } from "./FeaturesTestimonials";

const painPoints = [
  {
    problem: "Free autoresponders cap out fast",
    fix: "Start free with real automation — multi-step sequences, delays, and reply detection — not a crippled trial.",
    icon: DollarSign,
    iconColor: "text-destructive",
    iconBg: "bg-destructive/10",
  },
  {
    problem: "Autoresponders that ignore deliverability",
    fix: "Built-in inbox warm-up runs alongside your autoresponder, so automated follow-ups still land in the inbox.",
    icon: Flame,
    iconColor: "text-amber-500",
    iconBg: "bg-amber-500/10",
  },
  {
    problem: "Generic, robotic follow-up copy",
    fix: "AI writes each autoresponder step from contact data — no fill-in-the-blank templates.",
    icon: Bot,
    iconColor: "text-violet-500",
    iconBg: "bg-violet-500/10",
  },
];

const pillarCards = [
  {
    title: "Free autoresponder sequences",
    subtitle: "Start at no cost",
    body: "Build multi-step autoresponder sequences on the free plan — welcome emails, drip nurture, and follow-ups that pause automatically on reply.",
    icon: Timer,
    accent: "from-primary/25 to-blue-500/15",
  },
  {
    title: "Warm-up runs with your autoresponder",
    subtitle: "Deliverability layer",
    body: "Automated sequences are only useful if they land. Inbox warm-up runs continuously in the background, building trust while your autoresponder sends.",
    icon: Flame,
    accent: "from-emerald-500/25 to-teal-500/15",
  },
  {
    title: "AI-written, not templated",
    subtitle: "Smart autoresponses",
    body: "Every step in your autoresponder can be generated by AI from contact context — no generic form-letter tone.",
    icon: Sparkles,
    accent: "from-violet-500/25 to-purple-500/15",
  },
];

const featureGrid = [
  {
    title: "Multi-step autoresponder sequences",
    description:
      "Set up welcome series, drip campaigns, and follow-ups with time delays and conditional branches — free to start.",
    icon: Workflow,
    gradient: "from-primary/20 to-blue-500/15",
    iconColor: "text-primary",
    iconBg: "bg-primary/10",
    border: "hover:border-primary/40",
  },
  {
    title: "Automatic reply detection",
    description:
      "Sequences pause the instant a contact replies — no automated email ever gets sent to someone already in conversation.",
    icon: Reply,
    gradient: "from-cyan-500/20 to-blue-500/15",
    iconColor: "text-cyan-500",
    iconBg: "bg-cyan-500/10",
    border: "hover:border-cyan-500/40",
  },
  {
    title: "Built-in inbox warm-up",
    description:
      "Free plans include warm-up so your automated emails build sender reputation instead of burning it.",
    icon: Flame,
    gradient: "from-emerald-500/20 to-teal-500/15",
    iconColor: "text-emerald-500",
    iconBg: "bg-emerald-500/10",
    border: "hover:border-emerald-500/40",
  },
  {
    title: "AI-generated follow-ups",
    description:
      "Generate each autoresponder step from a short brief — subject lines, body copy, and personalized variants included.",
    icon: Sparkles,
    gradient: "from-violet-500/20 to-purple-500/15",
    iconColor: "text-violet-500",
    iconBg: "bg-violet-500/10",
    border: "hover:border-violet-500/40",
  },
  {
    title: "Unified reply inbox",
    description:
      "Every response to an autoresponder lands in one inbox. Tag, reply, and route hot leads without switching tools.",
    icon: MessageSquare,
    gradient: "from-amber-500/20 to-orange-500/15",
    iconColor: "text-amber-500",
    iconBg: "bg-amber-500/10",
    border: "hover:border-amber-500/40",
  },
  {
    title: "Delivery & engagement analytics",
    description:
      "See open, click, and reply rates for every autoresponder step, so you know exactly where sequences convert or drop off.",
    icon: BarChart3,
    gradient: "from-teal-500/20 to-emerald-500/15",
    iconColor: "text-teal-500",
    iconBg: "bg-teal-500/10",
    border: "hover:border-teal-500/40",
  },
  {
    title: "Domain health monitoring",
    description:
      "Track sender reputation per domain so automated sends never quietly damage deliverability.",
    icon: ShieldCheck,
    gradient: "from-rose-500/20 to-pink-500/15",
    iconColor: "text-rose-500",
    iconBg: "bg-rose-500/10",
    border: "hover:border-rose-500/40",
  },
  {
    title: "Multi-inbox rotation",
    description:
      "Distribute autoresponder volume across multiple connected inboxes to protect individual sender health.",
    icon: RefreshCw,
    gradient: "from-indigo-500/20 to-violet-500/15",
    iconColor: "text-indigo-500",
    iconBg: "bg-indigo-500/10",
    border: "hover:border-indigo-500/40",
  },
];

const workflowSteps = [
  {
    step: "01",
    title: "Sign up free",
    text: "Create an EmaReach account — no credit card required to start building your first autoresponder.",
  },
  {
    step: "02",
    title: "Connect your inbox",
    text: "Add Gmail, Google Workspace, or SMTP. Warm-up starts automatically to protect deliverability.",
  },
  {
    step: "03",
    title: "Build your sequence",
    text: "Add steps, set delays, and let AI draft the copy for welcome emails, nurture drips, or follow-ups.",
  },
  {
    step: "04",
    title: "Turn it on",
    text: "Your autoresponder runs continuously — new contacts enter the sequence automatically as they're added.",
  },
  {
    step: "05",
    title: "Track replies in one inbox",
    text: "Every response lands in EmaReach's unified inbox. Sequences pause automatically the moment someone replies.",
  },
];

const comparisonRows: { label: string; separate: string; emareach: string }[] = [
  { label: "Free tier automation", separate: "Single email, no sequences", emareach: "Multi-step sequences included" },
  { label: "Deliverability", separate: "Not addressed on free plans", emareach: "Warm-up built in from day one" },
  { label: "Copywriting", separate: "Manual templates", emareach: "AI-generated per step" },
  { label: "Reply handling", separate: "Manual inbox checking", emareach: "Auto-pause + unified inbox" },
  { label: "Analytics", separate: "Opens only, if any", emareach: "Opens, clicks, replies, placement" },
  { label: "Cost to scale", separate: "Paywall after a few hundred contacts", emareach: "Transparent plans, no surprise caps" },
];

const teamCards = [
  {
    team: "Solopreneurs & freelancers",
    result: "Automate welcome sequences and lead nurture without paying for enterprise software you don't need yet.",
    icon: Zap,
    color: "text-primary",
    bg: "bg-primary/10",
  },
  {
    team: "Small business owners",
    result: "Set up an autoresponder once and let it run — no daily manual follow-up required.",
    icon: Users2,
    color: "text-emerald-500",
    bg: "bg-emerald-500/10",
  },
  {
    team: "Growing teams outgrowing free tools",
    result: "Start free, then scale into paid tiers without migrating platforms or losing sequence history.",
    icon: Gauge,
    color: "text-violet-500",
    bg: "bg-violet-500/10",
  },
];

const statCards = [
  { value: "$0", label: "To start automating", sub: "no credit card required" },
  { value: "5-step", label: "Free sequence depth", sub: "welcome, nurture, follow-up" },
  { value: "92%", label: "Average inbox rate", sub: "with warm-up active" },
  { value: "1", label: "Platform for everything", sub: "autoresponder, warm-up, replies" },
];

const faqItems = [
  {
    q: "Is EmaReach's autoresponder really free?",
    a: "Yes. You can build and run multi-step autoresponder sequences on the free plan with no credit card required. See the pricing page for current free-tier limits on contacts and sends.",
  },
  {
    q: "What can I automate with the free autoresponder?",
    a: "Welcome sequences, lead nurture drips, and follow-up emails with time delays and conditional logic. Sequences pause automatically the moment a contact replies.",
  },
  {
    q: "Does the free plan include inbox warm-up?",
    a: "Yes. Warm-up is built into EmaReach from the free tier, so automated sends build sender reputation instead of risking it — something most free autoresponders skip entirely.",
  },
  {
    q: "Can AI write my autoresponder emails?",
    a: "Yes. Describe your goal and audience, and AI drafts each step of the sequence — subject lines and body copy — which you can edit before it goes live.",
  },
  {
    q: "What happens when someone replies to an automated email?",
    a: "The sequence pauses immediately and the reply lands in EmaReach's unified inbox, so no one who's already responded receives another automated follow-up.",
  },
  {
    q: "When do I need to upgrade from the free plan?",
    a: "Most users upgrade when they need more contacts, more inboxes, or advanced analytics. The free plan is built for real use, not just a demo — you can run production autoresponders on it.",
  },
  {
    q: "What inboxes work with the autoresponder?",
    a: "Gmail, Google Workspace, and any SMTP-compatible inbox. Free and paid plans both support multi-inbox rotation to distribute send volume.",
  },
];

function AutoresponderMock() {
  return (
    <div className="relative mx-auto mt-14 max-w-2xl">
      <div className="absolute -inset-1 rounded-2xl bg-gradient-to-r from-primary/30 via-emerald-500/20 to-violet-500/20 opacity-60 blur-2xl" />
      <div className="relative overflow-hidden rounded-2xl border border-border bg-card/95 shadow-2xl backdrop-blur-sm">
        <div className="flex items-center justify-between border-b border-border bg-muted/40 px-4 py-3">
          <span className="text-sm font-semibold">EmaReach — Autoresponder</span>
          <div className="flex items-center gap-2">
            <span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[11px] font-semibold text-emerald-600 dark:text-emerald-400">
              Free plan
            </span>
          </div>
        </div>
        <div className="p-5">
          <p className="mb-3 font-mono text-sm font-medium text-foreground">Welcome Series — 4 steps</p>
          <div className="space-y-2.5">
            {[
              { label: "Day 0 — Welcome email", status: "Sent", tone: "text-emerald-600 dark:text-emerald-400" },
              { label: "Day 2 — Getting started tips", status: "Scheduled", tone: "text-muted-foreground" },
              { label: "Day 5 — Feature highlight", status: "Scheduled", tone: "text-muted-foreground" },
              { label: "Day 9 — Check-in", status: "Paused (replied)", tone: "text-amber-600 dark:text-amber-400" },
            ].map((step) => (
              <div
                key={step.label}
                className="flex items-center justify-between rounded-lg border border-border/80 bg-muted/20 px-3 py-2 text-xs"
              >
                <span className="text-foreground">{step.label}</span>
                <span className={`font-semibold ${step.tone}`}>{step.status}</span>
              </div>
            ))}
          </div>
        </div>
        <div className="flex flex-wrap gap-2 border-t border-border/60 bg-muted/20 px-4 py-3 text-xs">
          <span className="rounded-full bg-primary/10 px-2 py-0.5 font-medium text-primary">AI-written</span>
          <span className="rounded-full bg-emerald-500/10 px-2 py-0.5 font-medium text-emerald-700 dark:text-emerald-300">Warm-up running</span>
        </div>
      </div>
    </div>
  );
}

function MidPageCta() {
  return (
    <section className="relative overflow-hidden py-16 lg:py-20">
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-primary/12 via-emerald-500/8 to-violet-500/8" />
      <div className="container relative mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
        <div className="rounded-3xl border border-primary/20 bg-gradient-to-br from-card to-primary/5 p-8 shadow-xl sm:p-12 lg:flex lg:items-center lg:justify-between lg:gap-10">
          <div className="mb-8 lg:mb-0">
            <h3 className="text-2xl font-bold tracking-tight sm:text-3xl">
              Automate follow-ups without paying upfront
            </h3>
            <p className="mt-3 max-w-xl text-muted-foreground">
              Free autoresponder sequences, built-in warm-up, and AI writing — start today, no card needed.
            </p>
          </div>
          <div className="flex shrink-0 flex-col gap-3 sm:flex-row lg:flex-col xl:flex-row">
            <Link
              href="/book-demo"
              className="gradient-primary inline-flex items-center justify-center gap-2 rounded-xl px-7 py-3.5 text-sm font-semibold text-primary-foreground shadow-lg shadow-primary/25 transition-all duration-200 hover:scale-[1.02] hover:brightness-105 active:scale-[0.98]"
            >
              Book a demo
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              href="/pricing"
              className="inline-flex items-center justify-center gap-2 rounded-xl border border-border bg-card px-7 py-3.5 text-sm font-semibold text-foreground shadow-sm transition-all duration-200 hover:border-primary/40 hover:bg-primary/5"
            >
              View pricing
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}

export function FreeEmailAutoresponderPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* ── HERO ── */}
      <section className="relative overflow-hidden pb-16 pt-20 lg:pb-24 lg:pt-28">
        <div className="pointer-events-none absolute inset-0 overflow-hidden">
          <div className="absolute -top-40 left-1/2 h-[700px] w-[700px] -translate-x-1/2 rounded-full bg-primary/6 blur-3xl" />
          <div className="absolute -right-40 top-20 h-96 w-96 rounded-full bg-emerald-500/7 blur-3xl" />
          <div className="absolute -left-40 bottom-0 h-80 w-80 rounded-full bg-violet-500/7 blur-3xl" />
        </div>

        <div className="container relative mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/8 px-4 py-1.5">
              <Timer className="h-3.5 w-3.5 text-primary" />
              <span className="text-xs font-semibold uppercase tracking-wider text-primary">
                Free Email Autoresponder
              </span>
            </div>

            <h1 className="mb-6 text-balance text-4xl font-bold leading-tight tracking-tight text-foreground sm:text-5xl lg:text-6xl">
              A free autoresponder that{" "}
              <span className="relative inline-block">
                <span className="relative z-10 bg-gradient-to-r from-primary to-emerald-500 bg-clip-text text-transparent">
                  actually reaches the inbox
                </span>
                <span className="absolute -bottom-1 left-0 right-0 h-0.5 rounded-full bg-gradient-to-r from-primary/60 to-emerald-500/60" />
              </span>
            </h1>

            <p className="mx-auto mb-4 max-w-2xl text-lg leading-relaxed text-muted-foreground">
              EmaReach&apos;s free email autoresponder includes multi-step sequences, AI-written follow-ups, and
              built-in inbox warm-up — no credit card, no crippled trial.
            </p>
            <p className="mx-auto mb-10 max-w-xl text-sm text-muted-foreground">
              Most free autoresponders ignore deliverability entirely. Ours builds sender reputation while it sends.
            </p>

            <div className="flex flex-col items-center justify-center gap-3 sm:flex-row">
              <Link
                href="/book-demo"
                className="gradient-primary inline-flex items-center justify-center gap-2 rounded-xl px-7 py-3.5 text-sm font-semibold text-primary-foreground shadow-lg shadow-primary/25 transition-all duration-200 hover:scale-[1.02] hover:brightness-105 active:scale-[0.98]"
              >
                Book a demo
                <ArrowRight className="h-4 w-4" />
              </Link>
              <Link
                href="/pricing"
                className="inline-flex items-center justify-center gap-2 rounded-xl border border-border bg-card px-7 py-3.5 text-sm font-semibold text-foreground/90 shadow-sm transition-all duration-200 hover:border-primary/40 hover:bg-primary/5 hover:text-primary"
              >
                View pricing
              </Link>
            </div>
          </div>

          <AutoresponderMock />

          <div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {statCards.map((s) => (
              <article
                key={s.label}
                className="rounded-2xl border border-border bg-card p-5 shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md text-center"
              >
                <p className="text-3xl font-black text-primary">{s.value}</p>
                <p className="mt-1 text-sm font-semibold text-foreground">{s.label}</p>
                <p className="mt-1 text-xs text-muted-foreground">{s.sub}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* ── PROBLEM / PAIN ── */}
      <section className="border-y border-border bg-muted/15 py-16 lg:py-24">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="mb-12 text-center">
            <span className="mb-3 inline-block text-xs font-semibold uppercase tracking-wider text-primary">
              The problem
            </span>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              &quot;Free&quot; autoresponders usually mean &quot;limited&quot;
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-lg text-muted-foreground">
              Single-email tools, no deliverability protection, and paywalls the moment your list grows. That&apos;s
              not automation — it&apos;s a demo.
            </p>
          </div>
          <div className="grid gap-6 lg:grid-cols-3">
            {painPoints.map((p) => (
              <article
                key={p.problem}
                className="rounded-2xl border border-border bg-card p-7 shadow-sm transition-all hover:border-primary/30 hover:shadow-md"
              >
                <div className={`mb-4 inline-flex rounded-xl ${p.iconBg} p-3 ${p.iconColor}`}>
                  <p.icon className="h-5 w-5" />
                </div>
                <h3 className="mb-2 text-base font-bold text-foreground">{p.problem}</h3>
                <p className="text-sm leading-relaxed text-muted-foreground">{p.fix}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* ── THREE PILLARS ── */}
      <section className="py-16 lg:py-24">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="mb-12 text-center">
            <span className="mb-3 inline-block text-xs font-semibold uppercase tracking-wider text-primary">
              Core pillars
            </span>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Real automation, free to start
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-lg text-muted-foreground">
              Sequences, deliverability, and AI writing — not a stripped-down trial.
            </p>
          </div>
          <div className="grid gap-6 lg:grid-cols-3">
            {pillarCards.map((p) => (
              <article
                key={p.title}
                className="relative overflow-hidden rounded-2xl border border-border bg-card p-8 shadow-sm transition-all hover:border-primary/30 hover:shadow-lg"
              >
                <div className={`pointer-events-none absolute inset-0 bg-gradient-to-br ${p.accent} opacity-40`} />
                <div className="relative">
                  <div className="mb-4 inline-flex rounded-xl bg-primary/10 p-3 text-primary">
                    <p.icon className="h-6 w-6" />
                  </div>
                  <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{p.subtitle}</p>
                  <h3 className="mt-1 text-xl font-bold">{p.title}</h3>
                  <p className="mt-3 text-sm leading-relaxed text-muted-foreground">{p.body}</p>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* ── FEATURE GRID ── */}
      <section className="border-y border-border bg-muted/15 py-16 lg:py-24">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="mb-12 text-center">
            <span className="mb-3 inline-block text-xs font-semibold uppercase tracking-wider text-primary">
              Feature breakdown
            </span>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Everything a real autoresponder needs
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-lg text-muted-foreground">
              No integrations required. No data silos. Everything ships together — free tier included.
            </p>
          </div>
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {featureGrid.map((item) => (
              <article
                key={item.title}
                className={`group relative overflow-hidden rounded-2xl border border-border bg-card p-6 shadow-sm transition-all duration-300 ${item.border} hover:-translate-y-0.5 hover:shadow-lg`}
              >
                <div
                  className={`pointer-events-none absolute inset-0 bg-gradient-to-br ${item.gradient} opacity-0 transition-opacity duration-300 group-hover:opacity-100`}
                />
                <div className="relative">
                  <div className={`mb-4 inline-flex rounded-xl ${item.iconBg} p-2.5 ${item.iconColor}`}>
                    <item.icon className="h-5 w-5" />
                  </div>
                  <h3 className="mb-2 text-sm font-semibold leading-snug">{item.title}</h3>
                  <p className="text-xs leading-relaxed text-muted-foreground">{item.description}</p>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ── */}
      <section className="py-16 lg:py-24">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="mb-12 text-center">
            <span className="mb-3 inline-block text-xs font-semibold uppercase tracking-wider text-primary">
              How it works
            </span>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              From signup to running sequence in five steps
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-lg text-muted-foreground">
              Set up once, on the free plan. It keeps running from there.
            </p>
          </div>

          <div className="grid gap-8 lg:grid-cols-2">
            <div className="rounded-2xl border border-border bg-card p-8 shadow-sm">
              <ol className="space-y-0">
                {workflowSteps.map((item, i) => (
                  <li key={item.step} className="flex gap-4">
                    <div className="flex flex-col items-center">
                      <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary ring-2 ring-primary/20">
                        {item.step}
                      </div>
                      {i < workflowSteps.length - 1 && <div className="my-1 w-px flex-1 bg-border" />}
                    </div>
                    <div className="pb-6 pt-1">
                      <p className="text-sm font-semibold text-foreground">{item.title}</p>
                      <p className="mt-0.5 text-sm leading-relaxed text-muted-foreground">{item.text}</p>
                    </div>
                  </li>
                ))}
              </ol>
            </div>

            <div className="flex flex-col gap-6">
              <div className="flex-1 rounded-3xl border border-border bg-gradient-to-br from-primary/10 via-card to-emerald-500/5 p-7 shadow-sm">
                <div className="mb-4 inline-flex rounded-xl bg-primary/15 p-3 text-primary">
                  <Flame className="h-7 w-7" />
                </div>
                <h3 className="text-xl font-bold">Warm-up runs alongside your autoresponder</h3>
                <p className="mt-3 text-sm text-muted-foreground">
                  Automated emails are only useful if they land. Warm-up builds domain trust continuously in the
                  background — even on the free plan.
                </p>
                <Link
                  href="/features/deliverability-warmup"
                  className="mt-5 inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline"
                >
                  Learn about our warm-up <ChevronRight className="h-3.5 w-3.5" />
                </Link>
              </div>
              <div className="rounded-3xl border border-border bg-card p-6 shadow-sm">
                <Clock className="mb-3 h-6 w-6 text-amber-500" />
                <h4 className="font-semibold">No sudden feature paywalls</h4>
                <p className="mt-2 text-sm text-muted-foreground">
                  Free-plan sequences, delays, and reply detection work the same way they will after you upgrade —
                  no rug pull as your list grows.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── COMPARISON TABLE ── */}
      <section className="border-y border-border bg-muted/15 py-16 lg:py-24">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="mb-10 text-center">
            <span className="mb-3 inline-block text-xs font-semibold uppercase tracking-wider text-primary">
              Why EmaReach
            </span>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Free autoresponders vs. EmaReach&apos;s free plan
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">
              Most &quot;free&quot; autoresponders are lead magnets for a paid upgrade. Ours is built to actually run your automation.
            </p>
          </div>
          <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
            <div className="grid grid-cols-3 gap-0 border-b border-border bg-muted/40 px-4 py-3.5 text-sm font-semibold sm:px-6">
              <span className="text-muted-foreground">Capability</span>
              <span className="text-center text-muted-foreground">Typical free tools</span>
              <span className="text-center text-primary">EmaReach</span>
            </div>
            {comparisonRows.map((row) => (
              <div
                key={row.label}
                className="grid grid-cols-3 gap-0 border-b border-border px-4 py-4 text-sm last:border-0 sm:px-6"
              >
                <span className="font-medium text-foreground">{row.label}</span>
                <span className="text-center text-muted-foreground">{row.separate}</span>
                <span className="text-center font-medium text-foreground">{row.emareach}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── WHO IT'S FOR ── */}
      <section className="py-16 lg:py-24">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="mb-12 text-center">
            <span className="mb-3 inline-block text-xs font-semibold uppercase tracking-wider text-primary">
              Who it&apos;s for
            </span>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Built for anyone starting out with automated email
            </h2>
          </div>
          <div className="grid gap-6 lg:grid-cols-3">
            {teamCards.map((item) => (
              <article
                key={item.team}
                className="flex gap-5 rounded-2xl border border-border bg-card p-7 shadow-sm transition-all duration-200 hover:border-primary/30 hover:shadow-md"
              >
                <div className={`mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${item.bg} ${item.color}`}>
                  <item.icon className="h-5 w-5" />
                </div>
                <div>
                  <p className="font-semibold text-foreground">{item.team}</p>
                  <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{item.result}</p>
                </div>
              </article>
            ))}
          </div>

          <div className="mt-8 rounded-2xl border border-border/60 bg-muted/20 p-5">
            <p className="mb-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Explore features</p>
            <div className="flex flex-wrap gap-2">
              {[
                { href: "/features/deliverability-warmup", label: "Deliverability & warm-up" },
                { href: "/features/campaign-automation-sequences", label: "Campaign automation" },
                { href: "/features/ai-writing-personalization", label: "AI writing & personalization" },
                { href: "/email-marketing-tool", label: "Email marketing tool" },
                { href: "/pricing", label: "Pricing" },
              ].map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  className="rounded-md border border-border bg-card px-2.5 py-1 text-xs font-medium text-foreground transition-colors hover:border-primary/40 hover:text-primary"
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>
        </div>
      </section>

      <FeaturesTestimonials />

      <MidPageCta />

      {/* ── FAQ ── */}
      <section className="border-y border-border bg-muted/15 py-16 lg:py-24">
        <div className="container mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <div className="mb-10 text-center">
            <span className="mb-3 inline-block text-xs font-semibold uppercase tracking-wider text-primary">FAQ</span>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Free autoresponder questions — answered
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-muted-foreground">
              Everything you need to know about EmaReach&apos;s free automated email plan.
            </p>
          </div>
          <Accordion type="single" collapsible className="w-full rounded-2xl border border-border bg-card px-4 shadow-sm sm:px-6">
            {faqItems.map((item, i) => (
              <AccordionItem key={item.q} value={`item-${i}`} className="border-border/80">
                <AccordionTrigger className="text-left text-base font-semibold hover:no-underline">
                  {item.q}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">{item.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* ── FINAL CTA ── */}
      <section className="relative overflow-hidden py-20 lg:py-28">
        <div className="pointer-events-none absolute inset-0 overflow-hidden">
          <div className="absolute -bottom-20 left-1/2 h-[500px] w-[500px] -translate-x-1/2 rounded-full bg-primary/8 blur-3xl" />
          <div className="absolute -left-20 top-10 h-60 w-60 rounded-full bg-emerald-500/8 blur-3xl" />
          <div className="absolute -right-20 top-10 h-60 w-60 rounded-full bg-violet-500/8 blur-3xl" />
        </div>

        <div className="container relative mx-auto max-w-3xl px-4 text-center sm:px-6 lg:px-8">
          <div className="mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/8 px-4 py-1.5">
            <TrendingUp className="h-3.5 w-3.5 text-primary" />
            <span className="text-xs font-semibold uppercase tracking-wider text-primary">
              Start automating for free
            </span>
          </div>

          <h2 className="mb-4 text-balance text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl">
            The free autoresponder that{" "}
            <span className="bg-gradient-to-r from-primary to-emerald-500 bg-clip-text text-transparent">
              doesn&apos;t skip deliverability
            </span>
          </h2>

          <p className="mb-10 text-lg leading-relaxed text-muted-foreground">
            EmaReach automates your follow-ups, warms up your inbox, and writes with AI — all on the free plan.
            Upgrade only when you actually need to.
          </p>

          <div className="flex flex-col items-center justify-center gap-3 sm:flex-row">
            <Link
              href="/book-demo"
              className="gradient-primary inline-flex items-center justify-center gap-2 rounded-xl px-8 py-4 text-sm font-semibold text-primary-foreground shadow-lg shadow-primary/30 transition-all duration-200 hover:scale-[1.02] hover:brightness-105 active:scale-[0.98]"
            >
              Book a demo
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              href="/pricing"
              className="inline-flex items-center justify-center gap-2 rounded-xl border border-border bg-card px-8 py-4 text-sm font-semibold text-foreground/90 shadow-sm transition-all duration-200 hover:border-primary/40 hover:bg-primary/5 hover:text-primary"
            >
              View pricing
            </Link>
          </div>

          <p className="mt-8 flex items-center justify-center gap-2 text-sm text-muted-foreground">
            <CheckCircle2 className="h-4 w-4 text-emerald-500" />
            Free autoresponder + warm-up + AI writing — book a demo to see it live.
          </p>
        </div>
      </section>

      <FeaturesCta />
    </div>
  );
}
